server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://117.50.183.16:3306/hmdb?useSSL=false&serverTimezone=UTC
    username: hmdb
    password: Dn4pnnx4XEdDhZN4
  redis:
    host: 117.50.183.16
    port: 6379
    password: lll111
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug